version: '3'

services:
  mysql:
    container_name: mysql
    build: ./mysql
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
  wordpress:
    container_name: wordpress
    depends_on:
      - mysql
    build: ./wordpress
    volumes:
      - ./html:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    depends_on:
       - wordpress
    ports:
       - '80:80'
       - '443:443'
    restart: always
    volumes:
       - ./ssl:/var/lib/https-portal
    environment:
      DOMAINS: '${DOMAIN} -> http://wordpress/'
      STAGE: ${ENV}
      TZ: 'Asia/Tokyo'
